// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBycGNEg_sfSE2T_6-_afE6uGT2FFthf48',
    appId: '1:48013660954:web:c54115ae8543f7dd4c12a3',
    messagingSenderId: '48013660954',
    projectId: 'findcameraman',
    authDomain: 'findcameraman.firebaseapp.com',
    storageBucket: 'findcameraman.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPeThxcn-e5H2NEKV1Us7H2gGMF2lYJl0',
    appId: '1:48013660954:android:f603bb2793068da04c12a3',
    messagingSenderId: '48013660954',
    projectId: 'findcameraman',
    storageBucket: 'findcameraman.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4-0i4HM65pq4Q_PNHxA0Snio5KJrDd3M',
    appId: '1:48013660954:ios:49bc51038225a6184c12a3',
    messagingSenderId: '48013660954',
    projectId: 'findcameraman',
    storageBucket: 'findcameraman.appspot.com',
    iosClientId: '48013660954-g8gsctgujqq8ucopihl2vap9fri3hm1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.findCameraman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4-0i4HM65pq4Q_PNHxA0Snio5KJrDd3M',
    appId: '1:48013660954:ios:e3f591147ac3b09c4c12a3',
    messagingSenderId: '48013660954',
    projectId: 'findcameraman',
    storageBucket: 'findcameraman.appspot.com',
    iosClientId: '48013660954-ohu6vfuq8h38hk2pml076726ktj8357o.apps.googleusercontent.com',
    iosBundleId: 'com.example.findCameraman.RunnerTests',
  );
}
